services:
  workouttracker-api:
    build: .
    container_name: workouttracker-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5065
    ports:
      - "5065:5065"
    volumes:
      - ./data:/app/data